<?php

namespace AppBundle\Repository;

/**
 * EnvironmentAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironmentAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
