<?php

namespace AppBundle\Repository;

/**
 * FamilyAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
