<?php

namespace AppBundle\Repository;

/**
 * healthAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
