<?php

namespace AppBundle\Repository;

/**
 * PersonalAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
