<?php

namespace AppBundle\Repository;

/**
 * PersonClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonClassRepository extends \Doctrine\ORM\EntityRepository
{
}
