admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /panel

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

apps:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /app

home:
    path:     /
    defaults: { _controller: AppBundle:Intro:index }

logout:
    path:     /logout
