admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /panel

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /app
