fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

apps:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /app

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

home:
    path:     /
    defaults: { _controller: AppBundle:Intro:index }

logout:
    path:     /logout


