
#Intro

Intro_companion:
    path:     /companion
    defaults: { _controller: AppBundle:Intro:companion }

Intro_instance:
    path:     /payment
    defaults: { _controller: AppBundle:Intro:payment }




#Areas

Areas_health:
    path:     /areas/health/{companion}
    defaults: { _controller: AppBundle:Areas:health, companion: null }

Areas_enviroment:
    path:     /areas/enviroment
    defaults: { _controller: AppBundle:Areas:enviroment }

Areas_personal:
    path:     /areas/personal
    defaults: { _controller: AppBundle:Areas:personal }

Areas_family:
    path:     /areas/family
    defaults: { _controller: AppBundle:Areas:family }


#Bureaucracy

Bureaucracy_instance:
    path:     /bureaucracy/instance
    defaults: { _controller: AppBundle:Bureaucracy:instance }

Bureaucracy_personal:
    path:     /bureaucracy/{id}
    defaults: { _controller: AppBundle:Bureaucracy:officialData, id: null }


#Default

test_room:
    path:     /testRoom
    defaults: { _controller: AppBundle:Default:index }

chat_room:
    path:     /chatRoom
    defaults: { _controller: AppBundle:Default:chat }
