FirstFase_index:
    path:     /
    defaults: { _controller: AppBundle:FirstFase:index }

form_witness:
    path:     /witness/form
    defaults: { _controller: AppBundle:FirstFase:new }

FirstFase_witness:
    path:     /witness
    defaults: { _controller: AppBundle:FirstFase:witness }

FirstFase_represesentant:
    path:     /represesentant
    defaults: { _controller: AppBundle:FirstFase:represesentant }

Fasedos_areas:
    path:     /areas
    defaults: { _controller: AppBundle:FirstFase:areas }

FirstFase_instance:
    path:     /instance
    defaults: { _controller: AppBundle:FirstFase:instance }

FirstFase_personal:
    path:     /personal
    defaults: { _controller: AppBundle:FirstFase:personal }
