#Default

test_room:
    path:     /testRoom
    defaults: { _controller: AppBundle:FirstFase:personal }

chat_room:
    path:     /chatRoom
    defaults: { _controller: AppBundle:Default:chat }





#Intro

Intro_index:
    path:     /
    defaults: { _controller: AppBundle:Intro:index }

Intro_companion:
    path:     /companion
    defaults: { _controller: AppBundle:Intro:companion }

#Areas

Areas_health:
    path:     /areas/health
    defaults: { _controller: AppBundle:Areas:health }

Areas_enviroment:
    path:     /areas/enviroment
    defaults: { _controller: AppBundle:Areas:enviroment }

Areas_personal:
    path:     /areas/personal
    defaults: { _controller: AppBundle:Areas:personal }

Areas_family:
    path:     /areas/family
    defaults: { _controller: AppBundle:Areas:family }

Areas_pendient_issues:
    path:     /areas/issues
    defaults: { _controller: AppBundle:Areas:issues }




#Bureaucracy

Bureaucracy_witness:
    path:  /witness
    defaults: { _controller: AppBundle:Bureaucracy:witness }

Bureaucracy_representant:
    path:     /representant
    defaults: { _controller: AppBundle:Bureaucracy:representant }

Bureaucracy_instance:
    path:     /instance
    defaults: { _controller: AppBundle:Bureaucracy:instance }

Bureaucracy_personal:
    path:     /personal
    defaults: { _controller: AppBundle:Bureaucracy:personal }
